spring:
    application:
        name: reserve-manage-app
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    flyway:
        enabled: true
        baseline-version: 0
        locations: "classpath:db/migration"
        baseline-on-migrate: true