CREATE TABLE IF NOT EXISTS reservations (
   id BIGINT PRIMARY KEY AUTO_INCREMENT,
   user_id BIGINT UNSIGNED NOT NULL,
   restaurant_id BIGINT UNSIGNED NOT NULL,
   reserve_date_time DATETIME NOT NULL,
   num_of_people INT NOT NULL,
   status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
   notes TEXT,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
   FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE
);